name: WeatherApp CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev libltdl-dev build-essential python3-dev python3-venv

    - name: Configure pip mirror
      run: |
        pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/
        pip config set global.trusted-host mirrors.aliyun.com

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install buildozer==1.5.0 kivy==2.3.1 requests==2.25.1 sdl2_ttf==2.0.18 cython==0.29.36 certifi

    - name: Install Android NDK
      run: |
        wget -q https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
        unzip -q android-ndk-r25c-linux.zip -d /opt
        echo "ndk_path=/opt/android-ndk-r25c" >> $GITHUB_ENV

    - name: Initialize Buildozer
      run: |
        buildozer init
        echo "[app]
        title = WeatherApp
        package.name = weatherapp
        package.domain = org.weatherapp
        source.dir = .
        source.include_exts = py,png,jpg,kv,atlas
        version = 0.1
        requirements = python3,kivy==2.3.1,requests==2.25.1,sdl2_ttf==2.0.18,certifi
        android.permissions = INTERNET
        android.api = 33
        android.minapi = 21
        android.sdk = 26
        android.ndk = 25c
        android.ndk_path = /opt/android-ndk-r25c
        orientation = portrait
        fullscreen = 0
        log_level = 2
        " > buildozer.spec

    - name: Build APK
      run: |
        buildozer android clean
        buildozer -v android debug deploy || echo "Build failed, check build.log for details"

    - name: Save Build Log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: build.log

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: weatherapp-apk
        path: bin/*.apk