name: Debug Build
true:
- push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install -r requirements.txt

        '
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '11'
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        ndk-version: 25.1.8937393
        cmake-version: 3.22.1
    - name: Configure Android SDK
      run: 'echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator"
        >> $GITHUB_PATH

        '
    - name: Build APK
      run: buildozer android debug
