name: Debug Build
true:
- push
- pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        ndk-version: 25c
        cmake-version: 3.22.1
    - name: Configure Android SDK
      run: 'echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH

        yes | sdkmanager --licenses

        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

        '
    - name: Build with Python
      run: 'pip install -r requirements.txt

        python setup.py build

        '
    - name: Upload build log
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-log
        path: 'build.log

          **/*.log'
