l
name: WeatherApp CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev libsdl2-dev libsdl2-ttf-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython==0.29.36
        pip install kivy==2.3.1 requests python-dotenv buildozer

    - name: Run WeatherApp test
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: |
        python weatherapp.py &
        sleep 5
        pkill python

    - name: Build APK
      run: |
        buildozer init
        echo "[app]
title = WeatherApp
package.name = weatherapp
package.domain = org.weatherapp
source.dir = .
source.include_exts = py,kv
version = 0.1
requirements = python3==3.10.13,kivy==2.3.1,requests,python-dotenv,openssl
orientation = portrait
osx.python_version = 3
osx.kivy_version = 2.3.1
android.api = 33
android.minapi = 21
android.ndk = 25b
android.sdk = 33
android.gradle_dependencies = 'com.android.tools.build:gradle:8.1.2'
android.permissions = INTERNET
fullscreen = 0
p4a.branch = master
android.allow_backup = false
android.accept_sdk_license = true
[buildozer]
log_level = 2" > buildozer.spec
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: weatherapp-apk
        path: bin/*.apk