name: WeatherApp CI
jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '11'
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: latest
        build-tools-version: 33.0.0
        platform-version: '33'
        ndk-version: 25.2.9519653
    - name: Accept licenses
      run: 'yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses ||
        true

        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33"
        "build-tools;33.0.0"

        '
    - name: Build with Gradle
      run: ./gradlew build
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install -r requirements.txt

        pip install buildozer'
    - name: Accept Android licenses
      run: 'yes | sdkmanager --licenses || true

        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"'
    - name: Build APK
      run: buildozer -v android debug deploy 2>&1 | tee build.log || { echo "Build
        failed, check build.log for details"; exit 1; }
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        P4A_RELEASE_KEYSTORE: ${{ secrets.P4A_RELEASE_KEYSTORE }}
        P4A_RELEASE_KEYALIAS: ${{ secrets.P4A_RELEASE_KEYALIAS }}
        P4A_RELEASE_KEYSTORE_PASSWD: ${{ secrets.P4A_RELEASE_KEYSTORE_PASSWD }}
        P4A_RELEASE_KEYALIAS_PASSWD: ${{ secrets.P4A_RELEASE_KEYALIAS_PASSWD }}
'on':
  push:
    branches:
    - main
