name: Debug Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        ndk-version: 25b
        cmake-version: 3.22.1
    - name: Install required Android components
      run: 'yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platform-tools"
        "platforms;android-33" "build-tools;33.0.0"

        '
    - name: Install Python dependencies
      run: 'python -m pip install --upgrade pip

        pip install -r requirements.txt

        pip install buildozer

        '
    - name: Build APK
      run: buildozer -v android debug
'on':
  push: {}
  pull_request: {}
