name: WeatherApp CI
jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install -r requirements.txt

        pip install buildozer'
    - name: Install Android SDK
      run: 'yes | sudo apt-get install -y openjdk-11-jdk

        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip

        unzip commandlinetools-linux-*.zip -d $ANDROID_HOME/cmdline-tools

        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

        echo ''export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin'' >> $GITHUB_ENV'
    - name: Accept Android licenses
      run: 'yes | sdkmanager --licenses || true

        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"'
    - name: Build with Buildozer
      run: buildozer -v android debug
      env:
        P4A_RELEASE_KEYSTORE: ${{ secrets.P4A_RELEASE_KEYSTORE }}
        P4A_RELEASE_KEYALIAS: ${{ secrets.P4A_RELEASE_KEYALIAS }}
        P4A_RELEASE_KEYSTORE_PASSWD: ${{ secrets.P4A_RELEASE_KEYSTORE_PASSWD }}
        P4A_RELEASE_KEYALIAS_PASSWD: ${{ secrets.P4A_RELEASE_KEYALIAS_PASSWD }}
'on':
  push:
    branches:
    - main
  pull_request: {}
  workflow_dispatch: {}
