name: WeatherApp CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:

    - name: Debug Android
      run: |
        echo "===== Environment Variables ====="
        env | grep ANDROID
        echo "\n===== Installed Tools ====="
        which sdkmanager || echo "sdkmanager not found"

    - name: Pre-check Android SDK
      run: |
        echo "ANDROID_HOME: $ANDROID_HOME"
        if [ ! -d "$ANDROID_HOME" ]; then
          echo "::error::ANDROID_HOME not set!"
          exit 1
        fi  

    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev libltdl-dev build-essential python3-dev python3-venv

    - name: Configure pip mirror
      run: |
        pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/
        pip config set global.trusted-host mirrors.aliyun.com

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install buildozer==1.5.0 kivy==2.3.1 requests==2.25.1 cython==0.29.36 certifi

    - name: Install Android NDK/SDK
      run: |
        wget -q https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
        unzip -q android-ndk-r25c-linux.zip -d /opt
        ls -la /opt/android-ndk-r25c || echo "NDK installation failed"
        echo "ndk_path=/opt/android-ndk-r25c" >> $GITHUB_ENV
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

    - name: Install Android SDK
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest -d /opt/android-sdk
        yes | /opt/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=/opt/android-sdk "platforms;android-33" "build-tools;33.0.0"
        echo "ANDROID_HOME=/opt/android-sdk" >> $GITHUB_ENV

    - name: Initialize Buildozer
      run: |
        buildozer init
        echo "[app]
        title = WeatherApp
        package.name = weatherapp
        package.domain = org.weatherapp
        source.dir = .
        source.include_exts = py,png,jpg,kv,atlas
        version = 0.1
        requirements = python3,kivy==2.3.1,requests==2.25.1,certifi
        android.permissions = INTERNET
        android.api = 33
        android.minapi = 21
        android.sdk = 33
        android.ndk = 25c
        android.ndk_path = /opt/android-ndk-r25c
        android.accept_sdk_license = True
        orientation = portrait
        fullscreen = 0
        log_level = 2
        android.gradle_download = True
        p4a.branch = master
        " > buildozer.spec

    - name: Build APK
      run: |
        buildozer android clean
        buildozer -v android debug deploy 2>&1 | tee build.log

    - name: Save Build Log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: build.log

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: weatherapp-apk
        path: bin/*.apk

        #v1