name: Debug Android Build
true:
- push
jobs:
  debug-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: temurin
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        ndk-version: 25c
        cmake-version: 3.22.1
    - name: Accept licenses
      run: 'yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses

        '
    - name: Build with debug info
      run: 'echo "ANDROID_HOME: $ANDROID_HOME"

        echo "PATH: $PATH"

        $ANDROID_HOME/tools/bin/sdkmanager --list

        '
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: debug-logs
        path: '${{ github.workspace }}/**/*.log

          ${{ github.workspace }}/**/*.txt'
