name: Debug Workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: temurin
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        cmdline-tools-version: '8.0'
        build-tools-version: 33.0.2
        platform-version: '33'
        ndk-version: 25.2.9519653
        disable-confirmation: true
'on':
  push: {}
