name: Debug Build
true:
- push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: latest
        build-tools-version: 34.0.0
        platform-version: '34'
        ndk-version: 25.2.9519653
        cmake-version: 3.22.1
    - name: Install Kivy dependencies
      run: 'sudo apt-get update

        sudo apt-get install -y python3-pip python3-dev ffmpeg libsdl2-dev libsdl2-image-dev
        libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev
        libavcodec-dev zlib1g-dev

        '
    - name: Install Python dependencies
      run: 'pip install --upgrade pip

        pip install kivy buildozer'
