l
name: WeatherApp CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev libltdl-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install buildozer kivy==2.3.1 requests==2.25.1 sdl2_ttf==2.0.18 cython==0.29.36 certifi

    - name: Initialize Buildozer
      run: |
        buildozer init
        echo "[app]
title = WeatherApp
package.name = weatherapp
package.domain = org.weatherapp
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.1
requirements = python3,kivy==2.3.1,requests==2.25.1,openssl,pyopenssl,certifi
android.permissions = INTERNET
android.api = 33
android.minapi = 21
android.sdk = 26
android.ndk = 25c
orientation = portrait
fullscreen = 0
" > buildozer.spec

    - name: Build APK
      run: |
        buildozer android clean
        buildozer -v android debug deploy 2>&1 | tee build.log

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: weatherapp-apk
        path: bin/*.apk