name: Debug Android Build
true:
- push
jobs:
  debug-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '11'
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        ndk-version: 25c
        cmake-version: 3.22.1
    - name: Accept Android licenses
      run: 'yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses

        '
    - name: Install required Android packages
      run: '$ANDROID_HOME/tools/bin/sdkmanager "platform-tools" "platforms;android-33"
        "build-tools;33.0.0"

        '
    - name: Verify Android tools
      run: 'echo "ANDROID_HOME: $ANDROID_HOME"

        ls -la $ANDROID_HOME/tools/bin/

        which sdkmanager'
