name: WeatherApp CI
jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Python dependencies
      run: "python -m pip install --upgrade pip\nif [ -f requirements.txt ]; then\n\
        \  pip install -r requirements.txt\nelse\n  echo \"requirements.txt not found,\
        \ installing default packages\"\n  pip install kivy buildozer\nfi\n"
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '11'
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: error-logs
        path: '**/*.log

          **/logs'
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install -r requirements.txt

        pip install buildozer'
    - name: Accept Android licenses
      run: 'yes | sdkmanager --licenses || true

        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"'
    - name: Build APK
      run: buildozer -v android debug deploy 2>&1 | tee build.log || { echo "Build
        failed, check build.log for details"; exit 1; }
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        P4A_RELEASE_KEYSTORE: ${{ secrets.P4A_RELEASE_KEYSTORE }}
        P4A_RELEASE_KEYALIAS: ${{ secrets.P4A_RELEASE_KEYALIAS }}
        P4A_RELEASE_KEYSTORE_PASSWD: ${{ secrets.P4A_RELEASE_KEYSTORE_PASSWD }}
        P4A_RELEASE_KEYALIAS_PASSWD: ${{ secrets.P4A_RELEASE_KEYALIAS_PASSWD }}
'on':
  push:
    branches:
    - main
