name: Debug Build
true:
- push
- pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '11'
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        ndk-version: 25b
        cmake-version: 3.22.1
    - name: Install Buildozer
      run: 'pip install --upgrade pip setuptools virtualenv

        pip install buildozer

        '
    - name: Build APK
      run: 'export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin

        buildozer -v android debug

        '
      env:
        ANDROID_HOME: /usr/local/lib/android/sdk
        ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
