name: Debug Build
true:
- push
- pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: latest
        build-tools-version: 34.0.0
        platform-version: '34'
        ndk-version: 25.2.9519653
        cmake-version: 3.22.1
    - name: Install Kivy dependencies
      run: "sudo apt-get update\nsudo apt-get install -y \\\n  python3-pip \\\n  build-essential\
        \ \\\n  git \\\n  python3-dev \\\n  ffmpeg \\\n  libsdl2-dev \\\n  libsdl2-image-dev\
        \ \\\n  libsdl2-mixer-dev \\\n  libsdl2-ttf-dev \\\n  libportmidi-dev \\\n\
        \  libswscale-dev \\\n  libavformat-dev \\\n  libavcodec-dev \\\n  zlib1g-dev\n"
    - name: Install Python dependencies
      run: 'python -m pip install --upgrade pip

        pip install kivy buildozer

        '
    - name: Build APK
      run: 'export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin

        buildozer android debug'
