name: Debug Build
true:
- push
- pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install -r requirements.txt

        '
    - name: Install Buildozer
      run: pip install buildozer
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '11'
    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        ndk-version: 25.1.8937393
        cmake-version: 3.22.1
    - name: Accept Android licenses
      run: 'yes | sdkmanager --licenses || true

        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

        '
    - name: Build with Gradle
      run: 'export ANDROID_HOME=$ANDROID_SDK_ROOT

        ./gradlew assembleDebug'
'on':
  push:
    branches:
    - main
  pull_request: {}
  workflow_dispatch: {}
