name: Debug Android Build
true:
- push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        ndk-version: 25c
        cmake-version: 3.22.1
    - name: Accept Android Licenses
      run: 'yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses

        '
    - name: Install Build Tools
      run: '$ANDROID_HOME/tools/bin/sdkmanager "build-tools;34.0.0" "platforms;android-34"

        '
    - name: Build with Kivy
      run: 'pip install -r requirements.txt

        python build.py android debug

        '
    - name: Upload build log
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-log
        path: 'build.log

          **/*.log'
