name: Debug Build
true:
- push
- pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '11'
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        ndk-version: 25c
        cmake-version: 3.22.1
    - name: Accept Android licenses
      run: 'yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses

        '
    - name: Build with Python
      run: 'python -m pip install --upgrade pip

        pip install -r requirements.txt

        python setup.py build

        '
    - name: Upload build log
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-log
        path: 'build.log

          **/build.log'
