name: WeatherApp CI
jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install -r requirements.txt

        '
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: temurin
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
    - name: Build APK
      run: 'buildozer android debug 2>&1 | tee build.log

        echo "BUILD_STATUS=$?" >> $GITHUB_ENV

        '
    - name: Upload build log
      if: always() && env.BUILD_STATUS != 0
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: build.log
        if-no-files-found: error
        retention-days: 5
    - name: Accept Android licenses
      run: 'yes | sdkmanager --licenses || true

        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"'
'on':
  push:
    branches:
    - main
