name: Debug Android Build
true:
- push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        ndk-version: 25c
        cmake-version: 3.22.1
    - name: Configure Android SDK
      run: 'echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH

        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

        echo "$ANDROID_HOME/emulator" >> $GITHUB_PATH

        yes | sdkmanager --licenses

        '
    - name: Build with Kivy
      run: 'pip install -r requirements.txt

        python -m buildozer android debug

        '
    - name: Upload build log
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-log
        path: 'buildozer.spec

          .buildozer/**/*.log

          '
        if-no-files-found: error
