name: Debug Build
true:
- push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Kivy
      run: 'python -m pip install --upgrade pip

        pip install kivy buildozer

        '
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: '11'
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
    - name: Accept Android licenses
      run: 'yes | sdkmanager --licenses

        '
    - name: Install required Android packages
      run: 'sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

        '
    - name: Build with Buildozer
      run: 'buildozer -v android debug

        '
      env:
        P4A_RELEASE_KEYSTORE: ${{ secrets.KEYSTORE }}
        P4A_RELEASE_KEYSTORE_PASSWD: ${{ secrets.KEYSTORE_PASS }}
        P4A_RELEASE_KEYALIAS_PASSWD: ${{ secrets.KEY_PASS }}
        P4A_RELEASE_KEYALIAS: ${{ secrets.KEY_ALIAS }}
