l
name: WeatherApp CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer kivy==2.3.1 requests==2.25.1 sdl2_ttf cython==0.29.36

    - name: Initialize Buildozer
      run: |
        buildozer init
        sed -i 's/title = My Application/title = WeatherApp/' buildozer.spec
        sed -i 's/package.name = myapp/package.name = weatherapp/' buildozer.spec
        sed -i 's/requirements = python3,kivy/requirements = python3,kivy==2.3.1,requests==2.25.1,pyopenssl,sdl2_ttf,openssl/' buildozer.spec
        sed -i 's/#android.ndk_path =/android.ndk_path = ~\/.buildozer\/android\/platform\/android-ndk-r25c/' buildozer.spec
        sed -i 's/#android.sdk_path =/android.sdk_path = ~\/.buildozer\/android\/platform\/android-sdk/' buildozer.spec
        echo "android.api = 33" >> buildozer.spec
        echo "android.minapi = 21" >> buildozer.spec

    - name: Build APK
      run: |
        buildozer android clean
        buildozer android debug deploy

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: weatherapp-apk
        path: bin/*.apk