name: Debug Build
true:
- push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        cmdline-tools-version: latest
        build-tools-version: 34.0.0
        platform-version: '34'
        ndk-version: 25.2.9519653
        cmake-version: 3.22.1
    - name: Install Kivy dependencies
      run: "sudo apt-get update\nsudo apt-get install -y python3-pip build-essential\
        \ git python3-dev ffmpeg \\\n  libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev\
        \ libsdl2-ttf-dev \\\n  libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev\
        \ zlib1g-dev\n"
    - name: Install Python dependencies
      run: 'python -m pip install --upgrade pip

        pip install kivy buildozer Cython==0.29.19'
